### ISSUE TITLE
[Feature Request]  A few ideas

### ISSUE THREAD

**Issue by PDXUser** [Receipt-Wrangler/receipt-wrangler-api#122]
**PDF Views**

We have used in the past, PDF copies of receipts, this has been our storage method for some time now.  In order for us to track expenses for our custodial adult child we need to keep track of expenditures and having the ability to either view an uploaded PDF or have it assimilate it would be key for us.

**Mobile Camera Uploads**
Mobile receipt upload via Camera - having the ability to take a picture of the receipt while on the road will make it so much easier.  No more lost receipts! 

**TimeZone Set**
I've not been able to set the timezone in the compose file so it thinks it's 9 hours ahead of my time zone.

**Comment by Noah231515** [comment]
@PDXUser 
PDF VIews: PDF support is for sure needed. I'll add it to ongoing development for this month.

Mobile Camera Uploads: This should be possible today, I have able to confirm this on Android devices at least. Are you using an IOS device by chance?

Timezone: Do you mean setting the timezone in the postgresql connection string?

**Comment by PDXUser** [comment]
We are 100% Android here for Mobile. 

Timezone - The logs are all recording 9 hours ahead of our zone (America/Pacific).

**Comment by Noah231515** [comment]
@PDXUser Gotcha, I'll check my logs out too and see what's up. 

When you're on a mobile device, uploading an image works the same way as it does on desktop. Is there a specific part of it that doesn't work for you?

**Comment by PDXUser** [comment]
I was asking for a way to use the phone's camera on the spot to take a picture of the receipt then upload said picture from the gallery. :)   While I know we can take a pic of the receipt, then browse the gallery to find it, having the ability to grab it all at the same time would be fantastic.

**Comment by Noah231515** [comment]
Thanks a bunch for the feedback. I have added these to the development backlog. However, I'm not too sure about the mobile camera piece. I'm wondering if it is a browser issue. I am using firefox, and am able to upload images directly from my camera. 

Feel free to contact me directly on discord to chat about this more.
