### ISSUE TITLE
[Feature Request] Unraid Container Template

### ISSUE THREAD

**Issue by blaine07** [Receipt-Wrangler/receipt-wrangler-api#124]
I would like to spin this up in Unraid. Is there any guidance on getting container(s) going in Unraid or anyone willing/capable of making container template?

**Comment by Noah231515** [comment]
At long last, this is in the unraid app store under the name, "ReceiptWrangler". Check it out!

**Comment by blaine07** [comment]
Can’t wait; will check it out asap. Thank YOU !
