### ISSUE TITLE
Ollama

### ISSUE THREAD

**Issue by roadkingvrod** [Receipt-Wrangler/receipt-wrangler-api#248]
I just wanted to see if you might support Ollama in addition to openai and gemini?  For us self hosted folks, it's a nice alternative.

**Comment by Noah231515** [comment]
Absolutely! Currently Receipt Wrangler supports self hosted servers that are open ai compatible (see https://receiptwrangler.io/docs/configuration/self-hosted-ai).

Ollama support will be coming soon. I am currently working on the next major version of Receipt Wrangler that is going to be released sometime early next month, along with a bunch of other goodies. Ollama support will be a part of that release, keep an eye out for it!

**Comment by roadkingvrod** [comment]
Awesome!  I'll be watching and provide feedback once I get it going.

**Comment by Noah231515** [comment]
Ollama has been added with the v5 release #265
