### ISSUE TITLE
Watch folder?

### ISSUE THREAD

**Issue by nothing2obvi** [Receipt-Wrangler/receipt-wrangler-api#272]
Hi, sorry, this isn't a bug.

Is there a way to add a watch/monitoring folder to Receipt-Wrangler? So if any PDF/JPG/PNG files, etc. that are in there just automatically get added to Receipt-Wrangler? I can't find anything about this in the documentation.

Thanks!

**Comment by Noah231515** [comment]
Hey nothing2obvi,

This is currently a backlog item and will enter development probably next month.

Cheers
Noah

**Comment by nothing2obvi** [comment]
Thanks!

**Comment by jcputney** [comment]
@Noah231515 I see you marked this as complete, but I can't find any documentation about how to use it. Is it in the application?

**Comment by Noah231515** [comment]
@jcputney This feature isn't in the app yet. This issue was closed since it is an item in the backlog already. No ETA as of now.
