### ISSUE TITLE
Make image size bigger or ability to download the attachment?

### ISSUE THREAD

**Issue by nothing2obvi** [Receipt-Wrangler/receipt-wrangler-api#273]
Is there a way to make the image size bigger or at least download the attachment? I uploaded a PDF and it's tiny.

Thank you!

**Comment by Noah231515** [comment]
Hey thanks for checking out Receipt Wrangler!


These both have been issues that have been hanging around that I haven't gotten to yet. At least, the image download. I finished up an enhancement that adds an image expander button so it can be viewed in full screen. Update to the latest version to check it out.

The download functionality is definitely needed. I'll add that too in the next few days.

Cheers
Noah

**Comment by nothing2obvi** [comment]
Thanks!

**Comment by nothing2obvi** [comment]
Both work great, thank you very much! Is there a reason why the preview area is so small and narrow? Why can't it be as big as say viewing an 8.5" x 11" PDF? I realize I can select `Expand image` or 'Download image' but I'm just wondering about the reasoning behind that. Thanks.

**Comment by nothing2obvi** [comment]
@Noah231515 

Sorry for the late response. Yes, something like that would be nice. Maybe a PDF reader? Not sure what the best choice is. While I have long receipts that would work with the current layout, I also have many 8.5 x 11 " receipts from online purchases or emails and they're difficult to read and are low quality / pixelated within Receipt Wrangler. I'd like to be able to use Receipt Wrangler to quickly reference my receipts, which requires reading them easily. I currently scan my receipts into both Paperless-ngx for readability and Receipt Wrangler for archiving, but it seems like a redundant workflow.

**Comment by Noah231515** [comment]
@nothing2obvi 

Got it. The ability to view large image previews has been added. There is a togglable button on the receipt images header to view large or small previews. There is a setting in user preferences to default it to large if you'd like.

Let me know if that helps!
