### ISSUE TITLE
EasyOCR is not installed

### ISSUE THREAD

**Issue by bdkuhman** [Receipt-Wrangler/receipt-wrangler-api#309]
The dependencies script seems to be broken in some places, 
When trying to run with EasyOCR, I get `Receipt data from AI: exec: "easyocr": executable file not found in $PATH`

There's a couple 
 `pip3: command not found`s in the docker build log after running `set-up-dependencies.sh`
 
 Using the latest monolith build.

**Comment by Noah231515** [comment]
This has been fixed. Update to the latest build monolith build to get the fix!
