### ISSUE TITLE
database container throwing out access denied errors

### ISSUE THREAD

**Issue by VorstrifeEdits** [Receipt-Wrangler/receipt-wrangler-api#318]
So I recently set-up the containers with mariadb, weird thing is everything seems to be working fine but I'm unable to figure out why exactly its spitting out these errors, any ideas?

2024-12-18  2:13:10 52 [Warning] Access denied for user 'root'@'localhost' (using password: NO)

**Comment by Noah231515** [comment]
That is odd. Are your environment variables set up correctly? https://receiptwrangler.io/docs/configuration/environment-variables for reference

**Comment by VorstrifeEdits** [comment]
From doing some digging I found it to be the health check variables causing an issue. I believe its because I am not running docker at a root level which it didn't seem to like. So I followed some of the advice and hardcoded the database password into the health check.

'["CMD", "mysqladmin", "-pmysupersecretpassword", "ping", "--silent"]'

Credit to this reddit thread:
https://www.reddit.com/r/receiptwrangler/comments/1cjyxvw/comment/l2qjg3w/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
